#!/usr/bin/env ruby
# encoding: utf-8

# May you recognize your weaknesses and share your strengths.
# May you share freely, never taking more than you give.
# May you find love and love everyone you find.

require 'json'
require 'pp'

# Show prettier output on interrupt (ctrl+c)
trap("INT") do |s|
   puts
   exit(s)
end

command = "grep -R '#{ARGV[0]}' #{ENV['WOMPT_LOG_DIR']}"
#puts command
`#{command}`.split("\n").each do |line|
   _,_,message = line.split ':', 3
   message = JSON.parse(message)
   puts "#{message['from']['name']}: #{message['msg']}"
end

